---
- name: generate systemd unit file
  become: true
  template:
    src: "{{ role_path }}/templates/ceph-mgr.service.j2"
    dest: /etc/systemd/system/ceph-mgr@.service
    owner: "root"
    group: "root"
    mode: "0644"

- name: systemd start mgr container
  systemd:
    name: ceph-mgr@{{ ansible_hostname }}
    state: started
    enabled: yes
    daemon_reload: yes
  changed_when: false
